CREATE TABLE IF NOT EXISTS question (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    userId INTEGER NOT NULL,
    title VARCHAR NOT NULL,
    text VARCHAR NOT NULL,
    published DATETIME NOT NULL,
    deleted DATETIME NULL,
    FOREIGN KEY (userId) REFERENCES user(id)
);
