CREATE TABLE IF NOT EXISTS review (
    revId INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    bookId INTEGER NOT NULL,
    score INTEGER NOT NULL,
    text VARCHAR,
    FOREIGN KEY (bookId) REFERENCES book(bookId)
);
